openapi: "3.0.2"
info:
  title: API сервер для сервиса аренды жилья «Шесть городов»
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: "1.0.0"

tags:
  - name: amenities
    description: Действия с типами удобств.
  - name: comments
    description: Действия с комментариями.
  - name: cities
    description: Действия с городами.
  - name: estates
    description: Действия с типом жилья.
  - name: offers
    description: Действия с объявлениями.
  - name: users
    description: Действия с пользователем.

paths:
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя.

      requestBody:
        description: Информация для создания нового пользователя.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createUser"
        required: true

      responses:
        "201":
          description: Пользователь зарегистрирован. Объект пользователя.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"

        "409":
          description: Пользователь с таким email уже существует.

  /users/login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля
      requestBody:
        description: Информация для авторизации пользователя.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginUser"
        required: true

      responses:
        "200":
          description: Пользователь авторизован.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"

        "401":
          description: Неправильный логин или пароль пользователя.

    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю
      responses:
        "200":
          description: OK

  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Загрузить изображение аватара
      description: Загружает изображение аватара пользователя. Изображение
        аватара должно быть в формате `png` или `jpg`.

      requestBody:
        description: Изображение для аватара.
        content:
          "image/jpeg":
            schema:
              type: string
              format: binary
          "image/png":
            schema:
              type: string
              format: binary

      responses:
        "200":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/avatar"

  /comments:
    post:
      tags:
        - comments
      summary: Создание нового комментария
      description: Добавляет новый комментарий
      requestBody:
        description: Информация для создания нового пользователя.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createComment"
        required: true

      responses:
        "201":
          description: Комментарий был создан. Объект комментария.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/comment"

    get:
      tags:
        - comments
      summary: Получение комментариев
      description: Возвращает список всех комментариев
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/comment"

  /comments/{commentId}:
    put:
      tags:
        - comments
      summary: Обновление комментария
      description: Обновляет указанный комментарий

      requestBody:
        description: Данные для обновления комментария.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createComment"

      responses:
        "201":
          description: Комментарий был обновлен. Объект обновленного комментария.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/comment"

    delete:
      tags:
        - comments
      summary: Удаление комментария
      description: Удаляет указанный комментарий
      responses:
        "204":
          description: No Content

  /cities:
    get:
      tags:
        - cities
      summary: Получение списка городов
      description: Возвращает список всех доступных городов
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/city"

        "404":
          description: Not found response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"

  /offers:
    post:
      tags:
        - offers
      summary: Создание нового предложения
      description: Добавляет в коллекцию новое предложение об аренде
      requestBody:
        description: Информация для создания нового предложения.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createOffer"

      responses:
        "201":
          description: Предложение было создано. Объект предложения.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/offer"

    get:
      tags:
        - offers
      summary: Получение всех предложений об аренде
      description: Возвращает список предложений

      responses:
        "200":
          description: Массив предложений.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/offer"

  /offers/{offerId}:
    put:
      tags:
        - offers
      summary: Обновление предложения об аренде
      description: Обновляет информацию о переданном предложении

      requestBody:
        description: Данные для обновления комментария.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createOffer"

      responses:
        "201":
          description: Предложение было обновлено. Объект обновленного предложения.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/offer"

    delete:
      tags:
        - offers
      summary: Удаление предложения
      description: Удаляет переданное предложение об аренде
      responses:
        "204":
          description: No Content

  /amenities:
    get:
      tags:
        - amenities
      summary: Получение типов удобств
      description: Возвращает список всех типов удобств
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/amenity"

        "404":
          description: Not found response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"

  /estates:
    get:
      tags:
        - estates
      summary: Получение типов предложений
      description: Возвращает список доступных типов предложений
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/estate"

        "404":
          description: Not found response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"

components:
  schemas:
    createUser:
      type: object

      properties:
        email:
          type: string
          example: ivan@gmail.com

        name:
          type: string
          example: Ivan

        avatarPath:
          type: string
          example: avatar.png

        password:
          type: string
          example: 123456

    loginUser:
      type: object

      properties:
        email:
          type: string
          example: ivan@gmail.com

        password:
          type: string
          example: 123456

    user:
      type: object

      properties:
        id:
          type: string
          example: 123qwerty4567890

        email:
          type: string
          example: ivan@gmail.com

    city:
      type: object

      properties:
        id:
          type: string
          example: 123qwerty4567890

        name:
          type: string
          example: Amsterdam

        latitude:
          type: string
          example: 52.370216

        longitude:
          type: string
          example: 4.895168

    estate:
      type: object

      properties:
        id:
          type: string
          example: 123qwerty4567890

        name:
          type: string
          example: apartment

    amenity:
      type: object

      properties:
        id:
          type: string
          example: 123qwerty4567890

        name:
          type: string
          example: Air conditioning

    errorMessage:
      type: object

      properties:
        message:
          type: string
          example: Текст ошибки

    avatar:
      type: object

      properties:
        id:
          type: string
          example: 123qwerty4567890
        path:
          type: string
          example: /images/best-avatar.jpg

    createComment:
      type: object

      properties:
        text:
          type: string
          example: Примерный текст комментария

    comment:
      type: object

      properties:
        id:
          type: string
          example: 123qwerty4567890
        text:
          type: string
          example: Текст комментария
        date:
          type: string
          format: date-time
          example: 2023-03-20T09:12:28Z
        rating:
          type: integer
          example: 5

    preview:
      type: string
      example: path/to/preview

    photo:
      type: string
      example: path/to/photo

    createOffer:
      type: object

      properties:
        title:
          type: string
          example: Сдам апартаменты в центре города.

        description:
          type: string
          example: Без посредников и комиссий. Квартира находится в центре города, рядом с остановками общественного транспорта

        postDate:
          type: string
          format: date-time
          example: 2023-03-20T09:12:28Z

        city:
          $ref: "#/components/schemas/city"

        preview:
          $ref: "#/components/schemas/preview"

        photos:
          type: array
          items:
            $ref: "#/components/schemas/photo"

        premium:
          type: boolean
          example: false

        favorite:
          type: boolean
          example: true

        rate:
          type: integer
          example: 3

        type:
          $ref: "#/components/schemas/estate"

        rooms:
          type: integer
          example: 3

        guests:
          type: integer
          example: 2

        price:
          type: integer
          example: 4000

        amenities:
          type: array
          items:
            $ref: "#/components/schemas/amenity"
        user:
          $ref: "#/components/schemas/user"

        commentsCount:
          type: integer
          example: 2

    offer:
      allOf:
        - type: object
          properties:
            id:
              type: string
              example: 123qwerty4567890
        - $ref: "#/components/schemas/createUser"
