openapi: "3.0.2"
info:
  title: API сервер для сервиса аренды жилья «Шесть городов»
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: "1.0.0"
servers:
  - url: https://api.server.test/v1
paths:
  /test:
    get:
      responses:
        "200":
          description: OK
tags:
  - name: account
    description: Действия с типом пользователя.
  - name: comments
    description: Действия с комментариями.
  - name: cities
    description: Действия с городами.
  - name: offers
    description: Действия с объявлениями.
  - name: services
    description: Действия с удобствами.
  - name: types
    description: Действия с типом жилья.
  - name: users
    description: Действия с пользователем.
